version: '3.8'

services:
  sog-php:
    image: sog-php:latest
    container_name: sog-php
    networks:
      - sog_net
      - localstart_default
    expose:
      - 9000

  sog-pgv:
    image: sog-pgv:latest
    container_name: sog-pgv
    depends_on:
      - sog-php
    networks:
      - sog_net
    ports:
      - "8083:80"
  sog-viewer:
    image: sog-viewer:latest
    container_name: sog-viewer
    networks:
      - sog_net
    ports:
      - "8093:80"

networks:
  sog_net:
    driver: bridge
  localstart_default:
    external: true