version: "3.7"
services:
  sog-pgv:
   
    build:
      args:
        NOME_PARTNER: sogei
      context: ../.
      dockerfile: ./sogei/nginx/Dockerfile
    container_name: sog-pgv
    ports:
      - 8083:80
    depends_on:
      - sog-php
    networks:
      - sog_net
      
  sog-php:
 
    build:
      args:
        NOME_PARTNER: sogei
      context: ../.
      dockerfile: ./sogei/php/Dockerfile
    container_name: sog-php
    command: bash -c "/bin/docker-entrypoint.sh"
    expose:
      - 9000
    networks:
      - sog_net
      - localstart_default
networks:
  sog_net:
    driver: bridge
  localstart_default:
    external: true